version: "3"

services:

  django:
    build: .
    command: python /project/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project/:/project/
      - ./sqlite/:/project/sqlite/
    ports:
      - "8000:8000"

  influxdb:
    image: docker.io/bitnami/influxdb:2
    ports:
      - 8086:8086
      - 8088:8088
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=bitnami123
      - INFLUXDB_ADMIN_USER_TOKEN=admintoken123
    volumes:
      - influxdb_data:/bitnami/influxdb

  clickhouse-server:
    image: yandex/clickhouse-server
    restart: unless-stopped
#    logging:
#      driver: none
    ports:
      - '8123:8123'
      - '9000:9000'
      - '9009:9009'

volumes:
  influxdb_data:
    driver: local
